---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.github.io/configuration/ and in linters documentation
APPLY_FIXES: none

EXCLUDED_DIRECTORIES:
  - common-tools
  - report
  - .git

ERROR_ON_MISSING_EXEC_BIT: true
SPELL_CSPELL_CONFIG_FILE: .cspell.yml

# Reporter
EMAIL_REPORTER: false
FILEIO_REPORTER: false
GITHUB_STATUS_REPORTER: false
JSON_REPORTER: true
PRINT_ALPACA: false
PRINT_ALL_FILES: false
SHOW_ELAPSED_TIME: true
